// <auto-generated />
namespace Treinaweb.Musicas.Acesso.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AdicaoMusica : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicaoMusica));
        
        string IMigrationMetadata.Id
        {
            get { return "202004151422469_AdicaoMusica"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
